// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB93_BmQrjshY5VbkfJD_zgIKyPHk84KUo',
    appId: '1:768055326481:web:8a2ba2bded1d4c7b1f3eb0',
    messagingSenderId: '768055326481',
    projectId: 'chat-app-584af',
    authDomain: 'chat-app-584af.firebaseapp.com',
    storageBucket: 'chat-app-584af.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnRBUr1xa0-MNfH5SNT-TIaDO5LokESmM',
    appId: '1:768055326481:android:01faffe4deee05b81f3eb0',
    messagingSenderId: '768055326481',
    projectId: 'chat-app-584af',
    storageBucket: 'chat-app-584af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAM0SiMI-RHdDuiFh4TP8n3G42raMG7N8',
    appId: '1:768055326481:ios:2c58076f3eb0e5161f3eb0',
    messagingSenderId: '768055326481',
    projectId: 'chat-app-584af',
    storageBucket: 'chat-app-584af.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAM0SiMI-RHdDuiFh4TP8n3G42raMG7N8',
    appId: '1:768055326481:ios:b1a9a634b73e97d81f3eb0',
    messagingSenderId: '768055326481',
    projectId: 'chat-app-584af',
    storageBucket: 'chat-app-584af.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
